google_analytics: "G-XXXXXXXXXX"
facebook_analytics: "XXXXXXXXXX"
pwa: true
google_fonts: 
  - "Fira Sans"

title: "Mototipp"
description: "Bei mototipp.de gibt's News rund ums motorisierte Zweirad. Immer aktuell, immer hochwertig, stets interessant. Vorbeischauen lohnt!"
url: "https://mototipp.de"
baseurl: ""
future: true
collections: 
  pages: 
    title: "Pages"
    output: true
    permalink: "/:title"

  posts: 
    title: "Posts"
    output: true
    permalink: "/news/:year/:month/:day/:title.html"
    scraping: 
      - 
        title: "Honda"
        user_prompt: "Erstelle eine News unter folgenden Parametern: - Ausgabe immer in deutscher Sprache - Gestaltung der erzeugten News immer mit diesen Text-Elementen: + Überschrift + kurzer, prägnanter Vorspann + Texthauptteil als Fließtext inklusive passender Zitate aus der Originalquelle sowie mit Quellennennung durch Textkonstruktionen wie \"nach Angaben von\", \"wie XY mitteilt\" etc. + Fazit mit den Kernaussagen aus dem Text in Bulletpoints - zwingender Verzicht auf werbliche Aussagen bzw. auf die ungeprüfte Übernahme werblicher Aussagen aus der Quelle"
        source: "https://www.honda.de/motorcycles/experience-honda/news-and-events.html"
        selector: ".gs.deskTwoQuarters.tabTwoThirds h3 > a"
        recurrence: "*/1 * * * *"
        times_generated: 7
        repo_id: "pockogalimugpja"



  stories: 
    title: "Stories"
    permalink: "/stories/:year/:month/:day/:title.html"
    output: true

  tipps: 
    title: "Tipps"
    output: true
    permalink: "/tipps/:title"

  companies: 
    title: "Companies"
    output: true
    permalink: "/firmen/:title"

  authors: 
    title: "Authors"
    output: true
    permalink: "/autoren/:title"

  categories: 
    title: "Rubriken"
    output: true
    permalink: "/:title"

  aside: 
    title: "Aside"
    output: false

  events: 
    title: "Events"
    output: true
    permalink: "/events/:year/:month/:title.html"

  articles: 
    scraping: 
      - 
        title: "Honda"
        user_prompt: "Erstelle eine News unter folgenden Parametern: - Ausgabe immer in deutscher Sprache - Gestaltung der erzeugten News immer mit diesen Text-Elementen: + Überschrift + kurzer, prägnanter Vorspann + Texthauptteil als Fließtext inklusive passender Zitate aus der Originalquelle sowie mit Quellennennung durch Textkonstruktionen wie \"nach Angaben von\", \"wie XY mitteilt\" etc. + Fazit mit den Kernaussagen aus dem Text in Bulletpoints - zwingender Verzicht auf werbliche Aussagen bzw. auf die ungeprüfte Übernahme werblicher Aussagen aus der Quelle"
        selector: ".gs.deskTwoQuarters.tabTwoThirds h3 > a"
        recurrence: "*/1 * * * *"
        times_generated: 7
        repo_id: "pockogalimugpja"




defaults: 
  - 
    scope: 
      path: ""
      type: "posts"

    values: 
      layout: "post"
      description: null
      author: "Stephan Krückel"
      issponsored: false
      sponsor: 
        - 
          company: "Firma"
          link: "http://website.com"
          image: "/uploads/sample.jpg"


      _inputs: 
        description: 
          type: "textarea"

        gallery[*].image: 
          type: "image"

        author: 
          type: "select"
          options: 
            values: "collections.authors"





  - 
    scope: 
      path: ""
      type: "companies"

    values: 
      layout: "company"
      description: null
      gallery: 
        - 
          image: "/uploads/sample.jpg"
          alt: "Bildbeschreibung"
          copyright: null


      _inputs: 
        description: 
          type: "textarea"

        gallery[*].image: 
          type: "image"




  - 
    scope: 
      path: ""
      type: "authors"

    values: 
      title: null
      description: null
      _inputs: 
        description: 
          type: "textarea"





cloudinary_image_base: "https://res.cloudinary.com/mototipp/image/upload"