google_analytics: "G-XXXXXXXXXX"
facebook_analytics: "XXXXXXXXXX"
pwa: true
google_fonts: 
  - "Fira Sans"

title: "Mototipp"
description: "Bei mototipp.de gibt's News rund ums motorisierte Zweirad. Immer aktuell, immer hochwertig, stets interessant. Vorbeischauen lohnt!"
url: "https://mototipp.de"
baseurl: ""
future: true
collections: 
  pages: 
    title: "Pages"
    output: true
    permalink: "/:title"

  posts: 
    title: "Posts"
    output: true
    permalink: "/news/:year/:month/:day/:title.html"
    scraping: 


  stories: 
    title: "Stories"
    permalink: "/stories/:year/:month/:day/:title.html"
    output: true

  tipps: 
    title: "Tipps"
    output: true
    permalink: "/tipps/:title"

  companies: 
    title: "Companies"
    output: true
    permalink: "/firmen/:title"

  authors: 
    title: "Authors"
    output: true
    permalink: "/autoren/:title"

  categories: 
    title: "Rubriken"
    output: true
    permalink: "/:title"

  aside: 
    title: "Aside"
    output: false

  events: 
    title: "Events"
    output: true
    permalink: "/events/:year/:month/:title.html"

  articles: 
    scraping: null


defaults: 
  - 
    scope: 
      path: ""
      type: "posts"

    values: 
      layout: "post"
      description: null
      author: "Stephan Kr√ºckel"
      issponsored: false
      sponsor: 
        - 
          company: "Firma"
          link: "http://website.com"
          image: "/uploads/sample.jpg"


      _inputs: 
        description: 
          type: "textarea"

        gallery[*].image: 
          type: "image"

        author: 
          type: "select"
          options: 
            values: "collections.authors"





  - 
    scope: 
      path: ""
      type: "companies"

    values: 
      layout: "company"
      description: null
      gallery: 
        - 
          image: "/uploads/sample.jpg"
          alt: "Bildbeschreibung"
          copyright: null


      _inputs: 
        description: 
          type: "textarea"

        gallery[*].image: 
          type: "image"




  - 
    scope: 
      path: ""
      type: "authors"

    values: 
      title: null
      description: null
      _inputs: 
        description: 
          type: "textarea"





cloudinary_image_base: "https://res.cloudinary.com/mototipp/image/upload"